### ISSUE TITLE
Azure signalr service support

### ISSUE THREAD

**Issue by pedicini** [dudipsh/nativescript-signalr-core#15]
**Is your feature request related to a problem? Please describe.**
I use nativescript angular and use Signalr Azure Service. Is it supported in this library? 
I have this url https://xxxxx.service.signalr.net/client/negotiate?hub=notifications
When the library creates the url wss omit access_tocken.
wss://xxxxx.service.signalr.net/client/?hub=notifications&id=xxxxxxx&access_token=

**Comment by dudipsh** [comment]
@pedicini 
check the newest version ( 1.0.12)
