### ISSUE TITLE
Azure SignalR Service with Azure functions

### ISSUE THREAD

**Issue by pedicini** [dudipsh/nativescript-signalr-core#16]
Hi,

first of all thanks for the quick reply to the other issue, I still have problems. I used the plugin with Asp Net Core 3 Signalr and it works, but with Azure SignalR Service with Azure functions, it doesn't work for me.

I use Nativescript with Angular, I updated the plugin to 1.0.12, the url creation continues to be non-compliant. The url it creates is as follows:

https://xxx.service.signalr.net/client/?hub=notifications/negotiate
the correct is
https://xxx.service.signalr.net/client/negotiate?hub=notifications

also the wss url is incorrect
wss: //xxxx.service.signalr.net/client/? hub = notifications? id =
in the url there are two '?' and does not add access_tocken

I modified the url https and wss with access tocken, it connects and immediately disconnects.

I would be so happy if you could help me out.

Thanks!
Ingmar

**Comment by alexgritton** [comment]
I'm submitting a pull request with a fix for this right now. I fixed it for non angular uses but didn't realize the fix didn't work for angular until I updated to the 1.0.12.
