### ISSUE TITLE
JS ERROR ReferenceError: Can't find variable: PSWebSocketDelegate on IOS

### ISSUE THREAD

**Issue by grgrcn** [dudipsh/nativescript-signalr-core#18]
Hi,
I try nativescript-signalr-core plugin on Android and work well. My app is NS-Vue and I use NS SideKick on W10. But if I launch Preview App from SideKick on my iPhone 6 the app crash with this error:
JS ERROR ReferenceError: Can't find variable: PSWebSocketDelegate

I noticed this in the NS console log:

[20-05-04 21:35:59.201] (CLI) Plugin nativescript-websockets is not included in preview app on device 1470236D-6571-4C8B-B5BD-466EB124EE09 and will not work.
[20-05-04 21:35:59.206] (CLI) In the app are used one or more NativeScript plugins with native dependencies.

The questions:

1) nativescript-signalr-core plugin run on IOS? 
2) If yes, how solve the problem?

Tks,
G.

**Comment by dudipsh** [comment]
@grgrcn 
1: the plugin works on ios and android
you need to run tns run ios/android
2:  didn't test it on "Preview App" - and i don't  plan on adding that
Feel free to contribute code to resolve the issue
