### ISSUE TITLE
Don´t have a main.tns.ts file in my project

### ISSUE THREAD

**Issue by stulli103** [dudipsh/nativescript-signalr-core#2]
Hi and thank you so much for creating this package. I am really hoping I can get it up and running.

In my project I don´t have a main.tns.ts file in it, is there any other file I can put the 
'
    declare var require;
    var WebSocket = require('nativescript-websockets');
'
in since I believe that is what is causing my errors.

I am using angular with typescript in my nativescript project.

The error I am getting is happening in node_modules when I run tns run android --bundle --env.uglify
![packageError](https://user-images.githubusercontent.com/24222367/57193768-1f48d380-6f3f-11e9-9f77-1a85601817db.JPG)

Thank you very much for your help and creating this package

Best regards, 
Siggi

**Comment by dudipsh** [comment]
Hi @stulli103 

Try to put the declaration on the top of the file that you used signalr

**Comment by stulli103** [comment]
Unfortunately that did not work. 

I am testing it like this
![image](https://user-images.githubusercontent.com/24222367/57194287-64700400-6f45-11e9-8638-a8fee2293927.png)

**Comment by dudipsh** [comment]
1: try to console.log the WebSocket ( to see if it's installed properly )
2: tns platform remove android and tns platform add android
3: delete the node_moduels and run npm install

**Comment by stulli103** [comment]
Hi again. 

I managed to get the program to run but unfortunately I am not able to receive data from the website that is also connected to my signalr server. 
I created a new project and can put it on GitHub and send it to you if you want to take a closer look. 

However my code is here if this suffices
`
     declare var require;
     var WebSocket = require('nativescript-websockets');

     import { Component, OnInit, NgZone } from "@angular/core";
     import { Item } from "./item";
     import { ItemService } from "./item.service";
     import { SignalrCore } from 'nativescript-signalr-core/angular';

     @Component({
      selector: "ns-items",
      moduleId: module.id,
      templateUrl: "./items.component.html"
     })
     export class ItemsComponent implements OnInit {
     items: Array<Item>;

    signalrCore: SignalrCore;

    constructor(
        private itemService: ItemService,
        private ngZone: NgZone
    ) { 
        this.signalrCore = new SignalrCore();
    }

    ngOnInit(): void {
        console.log("websocket: ", WebSocket);
        this.items = this.itemService.getItems();
        this.startConnection();
    }

    startConnection(): void {
        this.signalrCore.start(myUrlGoesInHere).subscribe((data) => {
            console.log("data equals: " + data);
            if (data == true){
                console.log("Made it here");
                this.addToGroup(1);
                this.addListener();
            }
        })
    }

    addToGroup = (groupName) => {
        console.log("adding to group");
        this.signalrCore.invoke('addtogroup', groupName)
        .then(data => console.log("then inside addToGroup"))
        .catch(err => console.error(err))
    }

    addListener = () => {
        console.log("Adding listener");
        this.signalrCore.on('broadcasteddata', (data) => {
            console.log("data recevied: ", data);
        })
     }
    }
`

And this is the console log result. As you can see, I never receive any answer back from my server. 
![image](https://user-images.githubusercontent.com/24222367/57198253-ecb7ce80-6f70-11e9-9ef5-792bf0a84b7f.png)

**Comment by stulli103** [comment]
One thought, might I need to add something to my startup.cs file in the signalr server so that he accepts the connection that your package uses?

**Comment by dudipsh** [comment]
Great, 
Try to add to in AndroidManifest file under the application Tag android:usesCleartextTraffic="true"

`<application android:name="com.tns.NativeScriptApplication" android:allowBackup="true" android:icon="@drawable/icon" android:label="@string/app_name" android:usesCleartextTraffic="true" android:theme="@style/AppTheme">`

> One thought, might I need to add something to my startup.cs file in the signalr server so that he accepts the connection that your package uses?`

Yes, check the startup.cs in 
https://github.com/dudipsh/CoreAndSignalR

**Comment by stulli103** [comment]
Unfortunately still no luck. Do you maybe have a typescript and Angular example/demo where you have made signalR work that I can fork from github and see if it works with my server?

**Comment by dudipsh** [comment]
here my basic app
https://github.com/dudipsh/tns-signalr-core-working-demo
@stulli103

**Comment by stulli103** [comment]
Thanks for that

I manage to connect to your server but not mine so that is at least something. 
Is it possible to see your ChatHub file to see if there is any difference between my hub and yours?

And thank you so much for helping me with this. 
I appreciate it immensely

**Comment by dudipsh** [comment]
sorry, but i can't share the backend code,
don't take reference from that (https://github.com/dudipsh/CoreAndSignalR) project expect the Startup.cs

**Comment by stulli103** [comment]
Alright no problem :)

**Comment by stulli103** [comment]
I found out the problem, I had to tweak the settings on my Azure SignalR service to allow CORS and set the server in a certain state. But now it works like a charm :D

Thank you so much for your help, and this package. It will be fun to work with it
