### ISSUE TITLE
Connection closes right after it was established.

### ISSUE THREAD

**Issue by ssaidev** [dudipsh/nativescript-signalr-core#20]
Hi All, 
I'm trying to convert a part of my Angular application into a nativescript mobile app. SignalR is the essential part of it. I'm using it to updated all other logged in users when a user makes a change in the part of the app he/she is logged into. My app works fine in the Chrome browser, but Chrome on Android is kind of leggy. It does not give the greatest UI experience. I think I can improve the experience if I make that part of the app a straight nativescript/angular application.

Not sure whether this is the nativescript-signalr-core bug, or it is just me not using it correctly. I've just followed the instructions laid down on the home page. I've been able to make the SignalR connection to my server. If I put a break point into 'connected' callback function, I can catch the connected event. That part seems to be working just fine. The issue I'm having is that the connection is not stable. It closes right after it gets established. I can also catch the disconnected event. 

This is the output I'm getting while debugging:

xxx isConnected?  true [file:///data/user/0/xxx/files/app/bundle.js]
xxx isConnected?  true

xxx isConnected?  true [file:///data/user/0/xxx/files/app/bundle.js]
xxx isConnected?  true

xxx isConnected?  true [file:///data/user/0/xxx/files/app/bundle.js]
xxx isConnected?  true

disconnected [file:///data/user/0/xxx/files/app/bundle.js]
disconnected

Unhandled Promise rejection: Error - Connection already close! ; Zone: <root> ; Task: setTimeout ; Value: Error - Connection already close! undefined [file:///data/user/0/xxx/files/app/vendor.js]
Unhandled Promise rejection: Error - Connection already close! ; Zone: <root> ; Task: setTimeout ; Value: Error - Connection already close! undefined
zone-nativescript.js:676
disconnected [file:///data/user/0/xxx/files/app/bundle.js]
disconnected

Unhandled Promise rejection: Error - Connection already close! ; Zone: <root> ; Task: setTimeout ; Value: Error - Connection already close! undefined [file:///data/user/0/xxx/files/app/vendor.js]
Unhandled Promise rejection: Error - Connection already close! ; Zone: <root> ; Task: setTimeout ; Value: Error - Connection already close! undefined
zone-nativescript.js:676
Error - Connection already close! [file:///data/user/0/xxx/files/app/bundle.js]
Error - Connection already close!

disconnected [file:///data/user/0/xxx/files/app/bundle.js]
disconnected

Unhandled Promise rejection: Error - Connection already close! ; Zone: <root> ; Task: setTimeout ; Value: Error - Connection already close! undefined [file:///data/user/0/xxx/files/app/vendor.js]
Unhandled Promise rejection: Error - Connection already close! ; Zone: <root> ; Task: setTimeout ; Value: Error - Connection already close! undefined

Not sure whether this is causing the issue, but I'd like to use Angular 9/10 in my project.

Would somebody please help me with a pointer or two on how to keep the connection stable after I establish it? If you require any info from me, not sure what extra I can give you. I've just followed what I found in the instructions on how to use it.

I'd appreciate your help very much.

Thank you...

**Comment by dudipsh** [comment]
@ssaidev 
Hey, 
please share your code and add a live example  
here https://play.nativescript.org

**Comment by ssaidev** [comment]
@dudipsh,
I appreciate you replying to me.

I was actually able to figure out my issue. Nothing to do with the plugin. Plugin works fine even with my app using the Angular 10. It was how I was initializing the connections to my different SignalR hubs.

Got it all working now. No issues anymore.

Thanks again.
