### ISSUE TITLE
background execution on iOS

### ISSUE THREAD

**Issue by MCorzo** [dudipsh/nativescript-signalr-core#21]
Hi @dudipsh, i don't know if this is a bug but i don't get the plugin work in background for iOS. It works fine on Android (even in a background service), but on iOS keep stucked after the  "start" method is called without any kind of response in the console, do you know if something like this is posible on iOS?

**Comment by dudipsh** [comment]
@MCorzo 
Hi

I don't remember if i test it on ios in the background
If you want you can create a demo in https://play.nativescript.org
and I will check it out.

In the meantime
If you have not deleted the ios platform try to remove/prepare/run
- ths remove ios
- tns prepare ios
- tns run ios

**Comment by MCorzo** [comment]
hello @dudipsh, I did not get my example to work in ns playground so create a private repository with the example and send you an invitation I hope it can help
