### ISSUE TITLE
SignalR connection closes in 3 minutes after Android tabled put into standby

### ISSUE THREAD

**Issue by ssaidev** [dudipsh/nativescript-signalr-core#23]
Hi,
I have an Android nativescript/angular application running on an Android tabled, using SignalR to send updates through server to other applications.

I've noticed that the SignalR connection automatically closes after the tablet is put into standby. I have a 5-sec heartbeat where I send the message to the ASP.NET Core WebAPI. I can see the response back for 3 minutes, but then the SignalR connection closes. It is almost like some kind of a timeout somewhere. And it is always 3 minutes.

This however does not happen when the tablet is powered on. The app just keeps communicating with the server and all works fine. Also, if I bring the tablet out of standby before it was in standby for 3 minutes, it just keeps working without any SignalR connection disruptions.

Not sure whether this is the bug. If it is not a bug, but working as designed, is there a way we can control this? To make it longer than 3 minutes, or to completely disable it?

I'd appreciate any help here.
Thanks...

**Comment by dudipsh** [comment]
@ssaidev 
Hi,

I think it's a natural behavior of Android,
Check out this link,
https://stackoverflow.com/questions/30525784/android-keep-service-running-when-app-is-killed
