### ISSUE TITLE
Authentication Token Usage

### ISSUE THREAD

**Issue by joeytitans** [dudipsh/nativescript-signalr-core#3]
Is there a way to create a signalr hub connection and pass it an authentication token using this plugin?  I'm basically trying to achieve the following in nativescript:

`hubConnection = new signalR.HubConnectionBuilder().withUrl("someUrl", { accessTokenFactory: () => authToken
     }).build();`

Thank you!
-Joey

**Comment by dudipsh** [comment]
@joeytitans 
Hi,
Right now the plugin doesn't support this behavior 
If you will provide me a server IP and a valid token I can try to add the ability to pass header key and token 

The result will be something like this
signalR.setHeader(''Authorization", "token123")

**Comment by dudipsh** [comment]
@joeytitans 
Now you can add a header.
