### ISSUE TITLE
Add support for access token authentication

### ISSUE THREAD

**Issue by bonfi7** [dudipsh/nativescript-signalr-core#5]
Is impossible to authenticate with access token(in header or querystring).
1)if access token is passed in headers, the negotiate call contains the headers but the next call is missing the headers(web socket). So the authentication will fail.
2)if access token is passed in query string the negotiate call create a malformed url(i.e. http://servername/hubname?accessToken=<token>/negotiate). 
This can be replicated with every url that contains querystring parameters.

A solution could be manage querystring parameters or enable headers in WebSocket calls

Thanks

**Comment by dudipsh** [comment]
@bonfi7 
I need server information so I can check it out
If you want, feel free to email me with the details
dudipsh@gmail.com
