### ISSUE TITLE
add err argument on xhr.onerror

### ISSUE THREAD

**Issue by coddicat** [dudipsh/nativescript-signalr-core#9]
xhr.onerror = function (err) {
            done(xhr.response || err);
        };

**Comment by dudipsh** [comment]
@coddicat 
 Hi,
Feel free to make a pull request, i will merge your changes to the package

**Comment by coddicat** [comment]
> @coddicat
> Hi,
> Feel free to make a pull request, i will merge your changes to the package

I cant, I dont have permissions, pushing returns 403

**Comment by dudipsh** [comment]
@coddicat 
[https://www.youtube.com/watch?v=rgbCcBNZcdQ](https://www.youtube.com/watch?v=rgbCcBNZcdQ)
